// Données mock de challenges pour développement
// Ces données seront remplacées par les appels API à /api/challenges en production
export const mockChallenges = [
  {
    id: 'icebreaker_001',
    name: 'Tour de présentation dynamique',
    category: 'icebreaker',
    objective: 'communication',
    duration: 8,
    type: 'Icebreaker interactif',
    tags: ['Présentation', 'Dynamique', 'Connexion'],
    description: 'Chacun se présente avec une anecdote amusante sélectionnée aléatoirement',
    config: {},
  },
  {
    id: 'copuzzle_001',
    name: 'CoPuzzle Live',
    category: 'escape-game',
    objective: 'cohesion',
    duration: 15,
    type: 'Puzzle collaboratif',
    tags: ['Collaboration', 'Temps limité', 'Réflexion'],
    description: 'Un puzzle collectif où tous les participants contribuent à assembler l\'image',
    config: {
      image: '',
      expectedCount: 4,
      duration: 600,
      warning: 60,
    },
  },
  {
    id: 'labyrinthe_001',
    name: 'Labyrinthe virtuel',
    category: 'escape-game',
    objective: 'cohesion',
    duration: 12,
    type: 'Navigation collective',
    tags: ['Navigation', 'Coopération', 'Défi'],
    description: 'Naviguer ensemble dans un labyrinthe virtuel en temps limité',
    config: {
      rows: 10,
      cols: 10,
      complexity: 'medium',
    },
  },
  {
    id: 'enigme_001',
    name: 'Énigme du trésor',
    category: 'logique-reflexion',
    objective: 'resolution-problemes',
    duration: 20,
    type: 'Énigme collaborative',
    tags: ['Déduction', 'Équipe', 'Créativité'],
    description: 'Une énigme complexe à résoudre en équipe avec indices progressifs',
    config: {},
  },
  {
    id: 'quiz_team_001',
    name: 'Quiz team',
    category: 'logique-reflexion',
    objective: 'resolution-problemes',
    duration: 10,
    type: 'Quiz compétitif',
    tags: ['Quiz', 'Compétition', 'Connaissance'],
    description: 'Un quiz interactif par équipe avec question bonus pour les vainqueurs',
    config: {},
  },
  {
    id: 'creation_001',
    name: 'Défi création',
    category: 'escape-game',
    objective: 'collaboration',
    duration: 25,
    type: 'Création collective',
    tags: ['Créativité', 'Collaboration', 'Défi'],
    description: 'Créer ensemble une œuvre artistique ou un projet dans le temps imparti',
    config: {},
  },
  {
    id: 'networking_001',
    name: 'Speed networking',
    category: 'icebreaker',
    objective: 'communication',
    duration: 12,
    type: 'Networking express',
    tags: ['Connexion', 'Rapide', 'Social'],
    description: 'Sessions courtes de rencontres en pairs pour favoriser les connexions',
    config: {},
  },
  {
    id: 'conflit_001',
    name: 'Résolution de conflit',
    category: 'logique-reflexion',
    objective: 'resolution-problemes',
    duration: 20,
    type: 'Atelier pratique',
    tags: ['Conflit', 'Communication', 'Résolution'],
    description: 'Simuler et discuter de scénarios de conflit pour développer des compétences',
    config: {},
  },
  {
    id: 'debrief_001',
    name: 'Débriefing structuré',
    category: 'logique-reflexion',
    objective: 'leadership',
    duration: 15,
    type: 'Réflexion collective',
    tags: ['Apprentissage', 'Feedback', 'Synthèse'],
    description: 'Structurer le débriefing avec des questions guidées et du temps de réflexion',
    config: {},
  },
];
